ROOT_DIR	= ../../
TYPE		= app
TARGET		= tast_gateway 
INSTALL_DIR	= $(ROOT_DIR)bin/
SRC_DIR		=  
INC_DIR		=
LIB_DIR		= 
SYS_LIB		=
LIB_DEPENDS	=  
OBJ_DEPENDS	= ../../libs/libCommonUtil.a \
../../libs/libCommonNet.a \
../../libs/libjsoncpp.a \
../../libs/libfastcgi.a
EXTRA_CFLAGS	= 
EXTRA_CXXFLAGS	= 

include $(ROOT_DIR)root.mk

