ROOT_DIR	= ../../
TYPE		= app
TARGET		= zhfq_downloadauth.cgi
INSTALL_DIR	= /var/www/cgi-bin/
SRC_DIR		=
INC_DIR		= ./ ../../
LIB_DIR		=
SYS_LIB		= -lcgicc
LIB_DEPENDS	= 
OBJ_DEPENDS	= ../../libs/libStdCGI.a \
              ../../libs/libCommonNet.a \
              ../../libs/libCommonUtil.a \
              ../../libs/libHttpUtil.a

EXTRA_CFLAGS	=
EXTRA_CXXFLAGS	=

include $(ROOT_DIR)root.mk
